kind: Service
apiVersion: v1
metadata:
  name: backstage-postgresql
  namespace: backstage
  uid: 6646aa7c-8e53-4737-8cd6-9ec413f550ba
  resourceVersion: '514624'
  creationTimestamp: '2025-01-26T02:59:12Z'
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.10.0
  annotations:
    meta.helm.sh/release-name: backstage
    meta.helm.sh/release-namespace: default
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: postgresql
